#!/usr/bin/env node
/**
 * ============================================================================
 * Legacy JSON -> Supabase migration script
 * ============================================================================
 *
 * Imports `backup_2026-07-10.json` into the Supabase Postgres database defined
 * by `202607240001_initial_schema.sql`.
 *
 * Tables touched (in dependency order):
 *   1. activities
 *   2. groups
 *   3. members
 *   4. member_activities
 *   5. attendance_sessions
 *   6. attendance_records
 *
 * NOTE ON `profiles` / `users`:
 *   The legacy JSON `users` array only contains a username + plaintext
 *   password (no email). Supabase Auth users cannot be created from that
 *   data without inventing throwaway emails and passwords, and doing so is
 *   out of scope for a data-only migration. Per the project instructions,
 *   this script does NOT synthesize new auth/profile rows. Instead it reads
 *   the UUID of the existing admin profile already provisioned in the target
 *   database (`select id from profiles limit 1`) and uses that UUID for every
 *   `created_by` / `updated_by` column required by the schema. If you need
 *   the legacy servant accounts to exist as real Supabase users, create them
 *   manually (or with a separate script using `supabase.auth.admin.createUser`)
 *   and assign them via the `group_servants` table afterwards.
 *
 * IDEMPOTENCY STRATEGY:
 *   The legacy JSON uses small numeric IDs while the Supabase schema expects
 *   `uuid` primary keys generated by `gen_random_uuid()`. To make this script
 *   safely re-runnable (no duplicate rows on a second run) without having to
 *   round-trip IDs from the database after every insert, we derive a
 *   *deterministic* UUID v5 for every legacy row from a fixed namespace + the
 *   table name + the legacy numeric ID. The same legacy row therefore always
 *   maps to the same UUID, so `upsert(...).on(id)` is naturally idempotent
 *   and foreign keys can be computed offline before any network call.
 *
 * ============================================================================
 */

'use strict';

require('dotenv').config();

const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');
const { v5: uuidv5 } = require('uuid');

// ----------------------------------------------------------------------------
// 1. CONFIGURATION & ENVIRONMENT VALIDATION
// ----------------------------------------------------------------------------

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

// Path to the legacy backup file. Overridable via env var for flexibility.
const BACKUP_FILE_PATH =
  process.env.BACKUP_FILE_PATH ||
  path.join(__dirname, '..', 'backup_2026-07-10.json');

// Fixed namespace UUID used to derive deterministic UUIDs for legacy rows.
// This is an arbitrary, constant UUID (v4) — it must NEVER change between
// runs, or previously imported rows will be duplicated instead of updated.
const UUID_NAMESPACE = '6f1f6f7e-9d3a-4b0a-8b0c-2a7e1c9f4d21';

// Refuse to run without the service role key — this operation needs to
// bypass Row Level Security, and the anon key cannot do that.
if (!SERVICE_ROLE_KEY) {
  console.error(
    '\n✖ Missing SUPABASE_SERVICE_ROLE_KEY environment variable.\n' +
      '  This script requires the service role key to bypass RLS while importing.\n' +
      '  Add it to your .env file and try again.\n'
  );
  process.exit(1);
}

if (!SUPABASE_URL) {
  console.error(
    '\n✖ Missing NEXT_PUBLIC_SUPABASE_URL environment variable.\n' +
      '  Add it to your .env file and try again.\n'
  );
  process.exit(1);
}

if (!fs.existsSync(BACKUP_FILE_PATH)) {
  console.error(`\n✖ Backup file not found at: ${BACKUP_FILE_PATH}\n`);
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ----------------------------------------------------------------------------
// 2. SMALL UTILITIES
// ----------------------------------------------------------------------------

/** Deterministically derive a UUID for a legacy row so re-runs upsert cleanly. */
function legacyUuid(table, legacyId) {
  return uuidv5(`${table}:${legacyId}`, UUID_NAMESPACE);
}

/** Convert an ISO datetime/date string to a plain `YYYY-MM-DD` date string. */
function toDateOnly(isoString) {
  if (!isoString) return null;
  return isoString.slice(0, 10);
}

/** Normalize possibly-null/undefined text fields to empty string or null. */
function textOrNull(value) {
  if (value === undefined || value === null) return null;
  const trimmed = String(value).trim();
  return trimmed.length ? trimmed : null;
}

/** Pretty console section header. */
function section(title) {
  console.log(`\n${title}`);
}

/** Simple stopwatch. */
function startTimer() {
  const start = process.hrtime.bigint();
  return () => {
    const end = process.hrtime.bigint();
    const ms = Number(end - start) / 1_000_000;
    if (ms < 1000) return `${ms.toFixed(0)}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
  };
}

// ----------------------------------------------------------------------------
// 3. LOAD & VALIDATE THE BACKUP FILE
// ----------------------------------------------------------------------------

function loadBackup() {
  let raw;
  try {
    raw = fs.readFileSync(BACKUP_FILE_PATH, 'utf-8');
  } catch (err) {
    throw new Error(`Could not read backup file: ${err.message}`);
  }

  let data;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Backup file is not valid JSON: ${err.message}`);
  }

  const expectedKeys = ['activities', 'groups', 'members', 'subs', 'users'];
  for (const key of expectedKeys) {
    if (!Array.isArray(data[key])) {
      console.warn(`⚠ Backup file is missing expected array "${key}" — treating as empty.`);
      data[key] = [];
    }
  }

  return data;
}

// ----------------------------------------------------------------------------
// 4. FETCH THE EXISTING ADMIN PROFILE UUID
// ----------------------------------------------------------------------------
//
// `attendance_sessions.created_by` and `attendance_records.updated_by` are
// NOT NULL foreign keys to `profiles.id`. Rather than hardcoding a UUID, we
// read the first available profile row already present in the target
// database (created by the `on_auth_user_created` trigger for the admin
// account that owns this Supabase project).

async function fetchAdminProfileId() {
  const { data, error } = await supabase
    .from('profiles')
    .select('id')
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(`Failed to read from "profiles": ${error.message}`);
  }

  if (!data) {
    throw new Error(
      'No rows found in "profiles". Create at least one admin user in ' +
        'Supabase Auth (which auto-populates "profiles" via the ' +
        'on_auth_user_created trigger) before running this import.'
    );
  }

  return data.id;
}

// ----------------------------------------------------------------------------
// 5. IMPORT: activities
// ----------------------------------------------------------------------------

async function importActivities(activities) {
  section('Importing activities...');

  const idMap = new Map(); // legacy numeric id -> uuid
  if (activities.length === 0) {
    console.log('  (no activities in backup, skipping)');
    return { idMap, imported: 0, errors: 0 };
  }

  const rows = activities.map((a) => {
    const id = legacyUuid('activities', a.id);
    idMap.set(a.id, id);
    return {
      id,
      name: textOrNull(a.name) || `activity-${a.id}`,
      icon: textOrNull(a.icon) || '⭐',
      color: textOrNull(a.color) || '#6366f1',
    };
  });

  const { data, error } = await supabase
    .from('activities')
    .upsert(rows, { onConflict: 'id' })
    .select('id');

  if (error) {
    console.error(`  ✖ Failed to import activities: ${error.message}`);
    return { idMap, imported: 0, errors: activities.length };
  }

  console.log(`  ✔ ${data.length} imported`);
  return { idMap, imported: data.length, errors: 0 };
}

// ----------------------------------------------------------------------------
// 6. IMPORT: groups
// ----------------------------------------------------------------------------

async function importGroups(groups) {
  section('Importing groups...');

  const idMap = new Map(); // legacy numeric id -> uuid
  if (groups.length === 0) {
    console.log('  (no groups in backup, skipping)');
    return { idMap, imported: 0, errors: 0 };
  }

  const rows = groups.map((g) => {
    const id = legacyUuid('groups', g.id);
    idMap.set(g.id, id);
    return {
      id,
      name: textOrNull(g.name) || `group-${g.id}`,
      grade: '', // not present in legacy data — schema default
      active: g.active !== undefined ? Boolean(g.active) : true,
      sort_order: Number.isFinite(g.order) ? g.order : 0,
    };
  });

  const { data, error } = await supabase
    .from('groups')
    .upsert(rows, { onConflict: 'id' })
    .select('id');

  if (error) {
    console.error(`  ✖ Failed to import groups: ${error.message}`);
    return { idMap, imported: 0, errors: groups.length };
  }

  console.log(`  ✔ ${data.length} imported`);
  return { idMap, imported: data.length, errors: 0 };
}

// ----------------------------------------------------------------------------
// 7. IMPORT: members
// ----------------------------------------------------------------------------

async function importMembers(members, groupIdMap) {
  section('Importing members...');

  const idMap = new Map(); // legacy numeric id -> uuid
  let skipped = 0;

  if (members.length === 0) {
    console.log('  (no members in backup, skipping)');
    return { idMap, imported: 0, errors: 0 };
  }

  const rows = [];
  for (const m of members) {
    const groupId = groupIdMap.get(m.groupId);
    if (!groupId) {
      console.warn(
        `  ⚠ Skipping member "${m.name}" (legacy id ${m.id}): missing group (legacy groupId ${m.groupId})`
      );
      skipped += 1;
      continue;
    }

    const id = legacyUuid('members', m.id);
    idMap.set(m.id, id);

    rows.push({
      id,
      group_id: groupId,
      full_name: textOrNull(m.name) || `member-${m.id}`,
      phone: textOrNull(m.phone),
      family_phone: textOrNull(m.familyPhone),
      address: textOrNull(m.address),
      school: textOrNull(m.school),
      notes: textOrNull(m.notes),
      active: m.active !== undefined ? Boolean(m.active) : true,
      joined_at: toDateOnly(m.joinedAt) || new Date().toISOString().slice(0, 10),
    });
  }

  if (rows.length === 0) {
    return { idMap, imported: 0, errors: skipped };
  }

  const { data, error } = await supabase
    .from('members')
    .upsert(rows, { onConflict: 'id' })
    .select('id');

  if (error) {
    console.error(`  ✖ Failed to import members: ${error.message}`);
    return { idMap, imported: 0, errors: members.length };
  }

  console.log(`  ✔ ${data.length} imported${skipped ? ` (${skipped} skipped — missing group)` : ''}`);
  return { idMap, imported: data.length, errors: skipped };
}

// ----------------------------------------------------------------------------
// 8. IMPORT: member_activities
// ----------------------------------------------------------------------------

async function importMemberActivities(members, memberIdMap, activityIdMap) {
  section('Importing member activities...');

  const rows = [];
  let skipped = 0;

  for (const m of members) {
    const legacyActivityIds = Array.isArray(m.activities) ? m.activities : [];
    if (legacyActivityIds.length === 0) continue;

    const memberId = memberIdMap.get(m.id);
    if (!memberId) {
      skipped += legacyActivityIds.length;
      continue;
    }

    for (const legacyActivityId of legacyActivityIds) {
      const activityId = activityIdMap.get(legacyActivityId);
      if (!activityId) {
        console.warn(
          `  ⚠ Skipping activity link for member (legacy id ${m.id}): missing activity (legacy id ${legacyActivityId})`
        );
        skipped += 1;
        continue;
      }
      rows.push({ member_id: memberId, activity_id: activityId });
    }
  }

  if (rows.length === 0) {
    console.log(`  (no member/activity links to import${skipped ? `, ${skipped} skipped` : ''})`);
    return { imported: 0, errors: skipped };
  }

  const { data, error } = await supabase
    .from('member_activities')
    .upsert(rows, { onConflict: 'member_id,activity_id' })
    .select('member_id');

  if (error) {
    console.error(`  ✖ Failed to import member activities: ${error.message}`);
    return { imported: 0, errors: rows.length };
  }

  console.log(`  ✔ ${data.length} imported${skipped ? ` (${skipped} skipped)` : ''}`);
  return { imported: data.length, errors: skipped };
}

// ----------------------------------------------------------------------------
// 9. IMPORT: attendance_sessions
// ----------------------------------------------------------------------------

async function importAttendanceSessions(subs, adminProfileId) {
  section('Importing attendance sessions...');

  const idMap = new Map(); // legacy sub.id -> uuid
  let skipped = 0;

  if (subs.length === 0) {
    console.log('  (no attendance sessions in backup, skipping)');
    return { idMap, imported: 0, errors: 0 };
  }

  const rows = [];
  for (const s of subs) {
    if (!s.dateISO) {
      console.warn(`  ⚠ Skipping session (legacy id ${s.id}): missing dateISO`);
      skipped += 1;
      continue;
    }

    // The schema enforces `extract(dow from attendance_date) = 5` (Friday).
    const day = new Date(`${s.dateISO}T00:00:00Z`).getUTCDay();
    if (day !== 5) {
      console.warn(
        `  ⚠ Skipping session (legacy id ${s.id}): date ${s.dateISO} is not a Friday, would violate DB check constraint`
      );
      skipped += 1;
      continue;
    }

    const id = legacyUuid('attendance_sessions', s.id);
    idMap.set(s.id, id);

    rows.push({
      id,
      attendance_date: s.dateISO,
      created_by: adminProfileId,
    });
  }

  if (rows.length === 0) {
    return { idMap, imported: 0, errors: skipped };
  }

  const { data, error } = await supabase
    .from('attendance_sessions')
    .upsert(rows, { onConflict: 'id' })
    .select('id');

  if (error) {
    console.error(`  ✖ Failed to import attendance sessions: ${error.message}`);
    return { idMap, imported: 0, errors: subs.length };
  }

  console.log(`  ✔ ${data.length} imported${skipped ? ` (${skipped} skipped)` : ''}`);
  return { idMap, imported: data.length, errors: skipped };
}

// ----------------------------------------------------------------------------
// 10. IMPORT: attendance_records
// ----------------------------------------------------------------------------

// Legacy Arabic field names -> schema boolean columns.
const RECORD_FIELD_MAP = {
  'حضور الخدمة': 'service_attended',
  'حضور القداس': 'mass_attended',
  'خدمة القداس': 'mass_service',
  الأعتراف: 'confession',
  'الأفتقاد التيليفوني': 'phone_follow_up',
  'الأفتقاد المنزلي': 'home_follow_up',
};

async function importAttendanceRecords(subs, sessionIdMap, memberIdMap, adminProfileId) {
  section('Importing attendance records...');

  let skipped = 0;
  const rows = [];

  for (const s of subs) {
    const sessionId = sessionIdMap.get(s.id);
    if (!sessionId) {
      // Session itself was skipped (bad date, etc.) — skip its records too.
      skipped += Array.isArray(s.records) ? s.records.length : 0;
      continue;
    }

    const records = Array.isArray(s.records) ? s.records : [];
    for (const r of records) {
      const memberId = memberIdMap.get(r.memberId);
      if (!memberId) {
        console.warn(
          `  ⚠ Skipping attendance record: unknown member (legacy id ${r.memberId}) in session ${s.dateISO}`
        );
        skipped += 1;
        continue;
      }

      const row = {
        id: legacyUuid('attendance_records', `${s.id}:${r.memberId}`),
        session_id: sessionId,
        member_id: memberId,
        updated_by: adminProfileId,
      };

      for (const [legacyField, column] of Object.entries(RECORD_FIELD_MAP)) {
        row[column] = Boolean(r[legacyField]);
      }

      rows.push(row);
    }
  }

  if (rows.length === 0) {
    console.log(`  (no attendance records to import${skipped ? `, ${skipped} skipped` : ''})`);
    return { imported: 0, errors: skipped };
  }

  // Batch in chunks to keep payloads reasonable for large historical datasets.
  const CHUNK_SIZE = 500;
  let imported = 0;
  let errors = skipped;

  for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
    const chunk = rows.slice(i, i + CHUNK_SIZE);
    const { data, error } = await supabase
      .from('attendance_records')
      .upsert(chunk, { onConflict: 'session_id,member_id' })
      .select('id');

    if (error) {
      console.error(
        `  ✖ Failed to import attendance records batch ${i / CHUNK_SIZE + 1}: ${error.message}`
      );
      errors += chunk.length;
      continue;
    }
    imported += data.length;
  }

  console.log(`  ✔ ${imported} imported${errors ? ` (${errors} skipped/errored)` : ''}`);
  return { imported, errors };
}

// ----------------------------------------------------------------------------
// 11. MAIN ORCHESTRATOR
// ----------------------------------------------------------------------------

async function main() {
  const totalTimer = startTimer();
  console.log('============================================================');
  console.log(' Supabase legacy data import');
  console.log('============================================================');

  const backup = loadBackup();

  const summary = {
    activities: { imported: 0, errors: 0 },
    groups: { imported: 0, errors: 0 },
    members: { imported: 0, errors: 0 },
    memberActivities: { imported: 0, errors: 0 },
    sessions: { imported: 0, errors: 0 },
    records: { imported: 0, errors: 0 },
  };

  // Resolve the existing admin profile UUID up front — every later step
  // that writes created_by/updated_by depends on it.
  let adminProfileId;
  try {
    adminProfileId = await fetchAdminProfileId();
    console.log(`\nUsing existing admin profile as audit user: ${adminProfileId}`);
  } catch (err) {
    console.error(`\n✖ ${err.message}`);
    process.exit(1);
  }

  // 1. activities
  const activitiesResult = await importActivities(backup.activities);
  summary.activities = activitiesResult;

  // 2. groups
  const groupsResult = await importGroups(backup.groups);
  summary.groups = groupsResult;

  // 3. members (depends on groups)
  const membersResult = await importMembers(backup.members, groupsResult.idMap);
  summary.members = membersResult;

  // 4. member_activities (depends on members + activities)
  const memberActivitiesResult = await importMemberActivities(
    backup.members,
    membersResult.idMap,
    activitiesResult.idMap
  );
  summary.memberActivities = memberActivitiesResult;

  // 5. attendance_sessions (depends on admin profile)
  const sessionsResult = await importAttendanceSessions(backup.subs, adminProfileId);
  summary.sessions = sessionsResult;

  // 6. attendance_records (depends on sessions + members)
  const recordsResult = await importAttendanceRecords(
    backup.subs,
    sessionsResult.idMap,
    membersResult.idMap,
    adminProfileId
  );
  summary.records = recordsResult;

  // ---------------------------------------------------------------------
  // Final summary
  // ---------------------------------------------------------------------
  const duration = totalTimer();
  console.log('\n============================================================');
  console.log(' Import summary');
  console.log('============================================================');
  console.log(`Activities:         ${summary.activities.imported} imported, ${summary.activities.errors} skipped/errored`);
  console.log(`Groups:             ${summary.groups.imported} imported, ${summary.groups.errors} skipped/errored`);
  console.log(`Members:            ${summary.members.imported} imported, ${summary.members.errors} skipped/errored`);
  console.log(`Member activities:  ${summary.memberActivities.imported} imported, ${summary.memberActivities.errors} skipped/errored`);
  console.log(`Sessions:           ${summary.sessions.imported} imported, ${summary.sessions.errors} skipped/errored`);
  console.log(`Attendance records: ${summary.records.imported} imported, ${summary.records.errors} skipped/errored`);
  console.log(`Duration:           ${duration}`);
  console.log('============================================================\n');

  const totalErrors =
    summary.activities.errors +
    summary.groups.errors +
    summary.members.errors +
    summary.memberActivities.errors +
    summary.sessions.errors +
    summary.records.errors;

  process.exit(totalErrors > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error('\n✖ Unexpected fatal error during import:');
  console.error(err.stack || err.message || err);
  process.exit(1);
});
